### ISSUE TITLE
字帖生成功能

### ISSUE THREAD

**Issue by SpiritLing** [nextstarproject/tools-fe#50]
参考：https://www.an2.net/zi/ 生成

支持功能

- [x] 文章字帖
- [x] 单行文字字帖
- [ ] 英文字帖（摇摆中）

packages:
- https://www.npmjs.com/package/react-to-print / https://github.com/gregnb/react-to-print

![Image](https://github.com/nextstarproject/tools-fe/assets/26963582/25134cc1-040e-473a-80f0-735a8b93de31)

**Comment by SpiritLing** [comment]
![image](https://github.com/nextstarproject/tools-fe/assets/26963582/e00f91ca-f23d-4ffe-84ad-bfc904c80a94)

样式模板，一行12个

**Comment by SpiritLing** [comment]
竖着15行

**Comment by SpiritLing** [comment]
拼音转换包：https://www.npmjs.com/package/pinyin-pro

**Comment by SpiritLing** [comment]
空芯字实现
![image](https://github.com/nextstarproject/tools-fe/assets/26963582/ec84ed70-2fa1-41df-97a0-d8b6e6d2c91b)

```css
.li {
  color: rgb(255, 255, 255);
  text-shadow: rgb(184, 184, 184) 1px 1px, rgb(184, 184, 184) -1px -1px, rgb(184, 184, 184) 1px -1px, rgb(184, 184, 184) -1px 1px;
}
```
